### PR TITLE
add list resource suggestions for azure

### PR DESCRIPTION
**Pull request by Juandavi1**

### CODE REVIEW

**Comment by Juandavi1** [comment]
@Lironrad you can review this PR ? could be helpfull

**Comment by Juandavi1** [comment]
@guyalt3 you can review this PR ? could be helpfull

**Comment by Lironrad** [comment]
Hi @Juandavi1, thanks for this PR.
I checked the code you wish to merge, the ocean AKS right sizing has a bit different configuration.
You can find the relevant information in [Spot's official API documentation](https://docs.spot.io/api/#operation/oceanAzureFilterRightSizingWithFilter).
We will add the relevant changes soon.

**Comment by Juandavi1** [comment]
Hi @Lironrad @guyalt3, 

I've been going through the documentation and it seems the url changed from the one used in the sdk. 
I updated it but it returns 404.

I'm testing the sdk with the changes I added, but I'm getting the same response.

In the sdk I see that a GET request is made and in the documentation it says that it is a POST but also responds 404. 
documentation may be out of date?

Can we continue working in this branch?

Thank you.

image


image

image

**Comment by Juandavi1** [comment]
https://github.com/spotinst/spotinst-sdk-go/pull/158

**Pull request closed without merging**
