### PR TITLE
Feature/azure rightsizing

### PR DESCRIPTION
**Pull request by Juandavi1**

### CODE REVIEW

**Comment by Juandavi1** [comment]
https://github.com/spotinst/spotinst-sdk-go/pull/149

**Comment by Juandavi1** [comment]
@guyalt3 @Lironrad https://github.com/spotinst/spotinst-sdk-go/pull/149#issuecomment-989454883 help please

**Comment by Juandavi1** [comment]
hello @zivmessing, we created this pr a month ago and received no response. 

could you help us? pleasee

**Comment by Lironrad** [comment]
Hi @Juandavi1, the right sizing APIs available in version [1.108.0](https://github.com/spotinst/spotinst-sdk-go/releases/tag/v1.108.0) along with usage examples for both [AWS](https://github.com/spotinst/spotinst-sdk-go/blob/main/examples/service/ocean/providers/aws/rightsizing/main.go) and [Azure](https://github.com/spotinst/spotinst-sdk-go/blob/main/examples/service/ocean/providers/azure/rightsizing/main.go).

**Pull request closed without merging**
